spring:
  application:
    name: EMPLOYEECLIENT
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  
    
server:
  port: 8081