spring:
  application:
    name: PROXYSERVICES

zuul:  prefix: /logical
  routes:
    resource:
      path: /api/v1/**
      url: http://localhost:1234/
      strip-prefix: false

server:  port: 7878
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka