server:
  port: 1234

spring:  application:    name: EMPLOYEESEARCHSERVICE

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8080/eureka